Improve CI (#83)

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,13 +1,22 @@
 #!/usr/bin/env bash
 
+# Exit if something fails
+set -e
+
+npm run lint
+npm run typescript
+
+# Unit test React 15 and collect coverage
 npm run react:15
 npm run unit -- --coverage
 mv coverage/coverage-final.json coverage/coverage-react15.json
 
+# Unit test React 16 and collect coverage
 npm run react:16
 npm run unit -- --coverage
 mv coverage/coverage-final.json coverage/coverage-react16.json
 
+# Combine unit test coverage
 mkdir -p .nyc_output
 npx istanbul-merge \
   --out .nyc_output/coverage-final.json \
@@ -16,11 +25,15 @@ npx istanbul-merge \
 
 rm -rf coverage
 
+# Report coverage to coveralls.io
 npx nyc report --reporter=text-lcov | npx coveralls
+# Report coverage so that danger-plugin-istanbul-coverage can find it
 npx nyc report --reporter=json-summary
 
+# PR info bot
 npm run danger
 
+# Attempt to run E2E tests
 if [ -z "$SAUCE_USERNAME" ] && [ -z "$SAUCE_ACCESS_KEY"]; then
   echo
   echo "ATTENTION"
